### ISSUE TITLE
Site fails to build with 2.6.2

### ISSUE THREAD

**Issue by manikmagar** [jbake-org/jbake.org#106]
While updating the docker image, I tried to build this site using 2.6.2 version. It is failing to bake with below error message -

```
22:39:17.436 INFO  org.jbake.app.Crawler - Processing [./content/docs/2.3.2/project-structure.ad]...  : new
22:39:17.464 INFO  org.jbake.app.Crawler - Processing [./content/docs/2.4.0/build-tool-integration.ad]...  : new
22:39:17.545 ERROR o.a.internal.JRubyAsciidoctor - org.jruby.RubyNoMethodError
22:39:17.546 INFO  c.o.orient.core.Orient - Orient Engine is shutting down...
22:39:17.547 INFO  c.o.orient.core.Orient - - shutdown storage: cache...
22:39:17.768 INFO  c.o.orient.core.Orient - OrientDB Engine shutdown complete
An unexpected error occurred: org.jruby.exceptions.RaiseException: (NoMethodError) asciidoctor: FAILED: <stdin>: Failed to load AsciiDoc document - undefined method `start_with?' for nil:NilClass
org.asciidoctor.internal.AsciidoctorCoreException: org.jruby.exceptions.RaiseException: (NoMethodError) asciidoctor: FAILED: <stdin>: Failed to load AsciiDoc document - undefined method `start_with?' for nil:NilClass
	at org.asciidoctor.internal.JRubyAsciidoctor.render(JRubyAsciidoctor.java:341)
	at org.asciidoctor.internal.JRubyAsciidoctor.render(JRubyAsciidoctor.java:448)
	at org.jbake.parser.AsciidoctorEngine.processAsciiDoc(AsciidoctorEngine.java:158)
	at org.jbake.parser.AsciidoctorEngine.processBody(AsciidoctorEngine.java:152)
	at org.jbake.parser.MarkupEngine.parse(MarkupEngine.java:118)
	at org.jbake.app.Parser.processFile(Parser.java:44)
	at org.jbake.app.Crawler.crawlSourceFile(Crawler.java:193)
	at org.jbake.app.Crawler.crawl(Crawler.java:112)
	at org.jbake.app.Crawler.crawl(Crawler.java:117)
	at org.jbake.app.Crawler.crawl(Crawler.java:117)
	at org.jbake.app.Crawler.crawl(Crawler.java:65)
	at org.jbake.app.Oven.bake(Oven.java:137)
	at org.jbake.launcher.Baker.bake(Baker.java:32)
	at org.jbake.launcher.Main.run(Main.java:97)
	at org.jbake.launcher.Main.run(Main.java:83)
	at org.jbake.launcher.Main.main(Main.java:56)
Caused by: org.jruby.exceptions.RaiseException: (NoMethodError) asciidoctor: FAILED: <stdin>: Failed to load AsciiDoc document - undefined method `start_with?' for nil:NilClass
	at RUBY.parse_section_title(uri:classloader:/gems/asciidoctor-1.5.7.1/lib/asciidoctor/parser.rb:1734)
	at RUBY.initialize_section(uri:classloader:/gems/asciidoctor-1.5.7.1/lib/asciidoctor/parser.rb:1564)
	at RUBY.next_section(uri:classloader:/gems/asciidoctor-1.5.7.1/lib/asciidoctor/parser.rb:290)
	at RUBY.parse(uri:classloader:/gems/asciidoctor-1.5.7.1/lib/asciidoctor/parser.rb:96)
	at RUBY.parse(uri:classloader:/gems/asciidoctor-1.5.7.1/lib/asciidoctor/document.rb:565)
	at RUBY.load(uri:classloader:/gems/asciidoctor-1.5.7.1/lib/asciidoctor.rb:1361)
	at RUBY.convert(uri:classloader:/gems/asciidoctor-1.5.7.1/lib/asciidoctor.rb:1473)
	at RUBY.convert(<script>:82)

```

Site successfully builds with previous versions until 2.6.1.

**Comment by ancho** [comment]
Seems to be a problem with asciidoctorj 1.5.7. Building v2.6.2 with 1.5.6 and asciidoctorj-diagram 1.5.8 (15.9 has a implicit dependency to asciidoctorj 1.5.7) does not throw this exception.

Maybe we missed a configuration change or a bugfix form 1.5.6 to 1.5.7.

**Comment by jonbullock** [comment]
I could have sworn I tested jbake.org using the new release before I pushed it, but maybe not. 

Thanks guys for catching this 👍

**Comment by ancho** [comment]
That's the weird thing here. I'm sure I did that, too.

**Comment by manikmagar** [comment]
But now it is failing for you guys too, right? Just to make sure it is not something in my environment 🙂.
  

  
  

  
  
>
